AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  openapi_to_postman

  Deploys a lambda function for converting OpenAPI Specs to Postman Collections, with accompanying API Gateway endpoint.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  OpenApiToPostmanFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      MemorySize: 512
      CodeUri: openapi-to-postman/
      Handler: app.handler
      Runtime: nodejs14.x
      Events:
        OpenApiToPostman:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
            RequestParameters:
              - method.request.querystring.openapi:
                  Required: true
                  Caching: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  OpenApiToPostmanApi:
    Description: "API Gateway endpoint URL for Prod stage for OpenApiToPostman function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  OpenApiToPostmanFunction:
    Description: "OpenApiToPostmanFunction Lambda Function ARN"
    Value: !GetAtt OpenApiToPostmanFunction.Arn
  OpenApiToPostmanFunctionIamRole:
    Description: "Implicit IAM Role created for OpenApiToPostman function"
    Value: !GetAtt OpenApiToPostmanFunctionRole.Arn
